/**
 * Step 3 — choose the workflow structure.
 *
 * The cards carry the weight of this step: each one shows a real miniature of
 * the topology it would produce, generated by the same layout engine as the
 * full diagram, so what the user previews is what they get.
 */

import { useMemo, useState } from 'react';

import { COMPLEXITY_LABELS, STRUCTURE_PRESETS } from '../../../model/catalog';
import { applyTopology, createGauntlet } from '../../../model/defaults';
import type { GauntletConfig, StructurePreset, TopologyKind } from '../../../model/types';
import { MiniDiagram } from '../../diagram/WorkflowDiagram';
import { Badge, Button, Callout, Dialog } from '../../ui';
import { Check, Users } from '../../ui/Icons';
import './Step3Structure.css';

interface Props {
  config: GauntletConfig;
  update: (updater: (config: GauntletConfig) => GauntletConfig) => void;
}

export function Step3Structure({ config, update }: Props) {
  const [details, setDetails] = useState<StructurePreset | null>(null);

  // One throwaway config per topology, so the miniatures are genuinely
  // generated rather than drawn by hand.
  const previews = useMemo(() => {
    const map = new Map<TopologyKind, GauntletConfig>();
    STRUCTURE_PRESETS.forEach((preset) => {
      map.set(preset.kind, applyTopology(createGauntlet({ agents: [] }), preset.kind));
    });
    return map;
  }, []);

  const select = (kind: TopologyKind) => {
    if (kind === config.topology) return;
    update((c) => applyTopology(c, kind));
  };

  // Warn only if the user has genuinely edited the roster away from a template.
  const customised = config.agents.some((a) => a.notes || a.permissions.write.length > 0);

  return (
    <div className="stack-lg">
      {customised && (
        <Callout tone="warn" title="Changing the structure rebuilds your agents">
          You have customised the roster. Picking a different structure replaces it with that
          structure's template, and your per-agent changes will be lost.
        </Callout>
      )}

      <div className="structure-grid" role="radiogroup" aria-label="Workflow structure">
        {STRUCTURE_PRESETS.map((preset) => {
          const preview = previews.get(preset.kind);
          const selected = config.topology === preset.kind;
          return (
            <div
              key={preset.kind}
              className="structure-card"
              data-selected={selected}
              role="radio"
              aria-checked={selected}
              aria-label={`${preset.name}. ${preset.tagline}`}
              tabIndex={0}
              onClick={() => select(preset.kind)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault();
                  select(preset.kind);
                }
              }}
            >
              <div className="structure-card-head">
                <h3 className="structure-card-title">{preset.name}</h3>
                {selected && (
                  <span className="structure-selected">
                    <Check size={12} />
                    <span className="visually-hidden">Selected</span>
                  </span>
                )}
              </div>

              <p className="structure-card-tagline">{preset.tagline}</p>

              <div className="structure-card-diagram">
                {preview && (
                  <MiniDiagram agents={preview.agents} edges={preview.communication.edges} />
                )}
              </div>

              <dl className="structure-facts">
                <div>
                  <dt>Agents</dt>
                  <dd>
                    <Users size={11} /> {preset.agentCountLabel}
                  </dd>
                </div>
                <div>
                  <dt>Effort</dt>
                  <dd>{COMPLEXITY_LABELS[preset.complexity]}</dd>
                </div>
                <div>
                  <dt>Cost</dt>
                  <dd>{preset.costLabel}</dd>
                </div>
              </dl>

              <p className="structure-line">
                <span className="structure-line-key">Approval</span>
                {preset.approvalSummary}
              </p>
              <p className="structure-line">
                <span className="structure-line-key">Best for</span>
                {preset.bestFor.join(', ')}
              </p>

              <Button
                size="sm"
                variant="ghost"
                className="structure-more"
                onClick={(e) => {
                  e.stopPropagation();
                  setDetails(preset);
                }}
              >
                Advantages and risks
              </Button>
            </div>
          );
        })}
      </div>

      <Dialog
        open={details !== null}
        onOpenChange={(open) => !open && setDetails(null)}
        title={details?.name ?? ''}
        description={details?.description}
      >
        {details && (
          <div className="stack">
            <DetailBlock title="How it flows">
              <p className="text-sm text-secondary">{details.flowSummary}</p>
            </DetailBlock>
            <DetailBlock title="Advantages">
              <ul className="stack-sm text-sm text-secondary">
                {details.advantages.map((a) => (
                  <li key={a}>• {a}</li>
                ))}
              </ul>
            </DetailBlock>
            <DetailBlock title="Risks">
              <ul className="stack-sm text-sm text-secondary">
                {details.risks.map((r) => (
                  <li key={r}>• {r}</li>
                ))}
              </ul>
            </DetailBlock>
            <DetailBlock title="Best for">
              <div className="row-wrap">
                {details.bestFor.map((b) => (
                  <Badge key={b}>{b}</Badge>
                ))}
              </div>
            </DetailBlock>
          </div>
        )}
      </Dialog>
    </div>
  );
}

function DetailBlock({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="eyebrow" style={{ marginBottom: 'var(--space-2)' }}>
        {title}
      </p>
      {children}
    </div>
  );
}
