/**
 * Step 6 — the approval policy.
 *
 * Every policy shows its practical consequence, and the panel at the bottom
 * always states the resulting completion condition in one sentence. That
 * sentence is generated by the same function the prompt uses, so what the user
 * reads here is literally what the agent will be told.
 */

import { APPROVAL_POLICIES, approvalById, roleById } from '../../../model/catalog';
import { completionSentence, derive } from '../../../engine/derive';
import type { ApprovalPolicyKind, GauntletConfig } from '../../../model/types';
import { Badge, Callout, NumberInput, Select, Toggle } from '../../ui';
import { Check } from '../../ui/Icons';
import './Step6Approval.css';

interface Props {
  config: GauntletConfig;
  update: (updater: (config: GauntletConfig) => GauntletConfig) => void;
  advanced: boolean;
}

export function Step6Approval({ config, update, advanced }: Props) {
  const ctx = derive(config);
  const approval = config.approval;
  const reviewers = ctx.integrator ? [...ctx.reviewers, ctx.integrator] : ctx.reviewers;

  const patchApproval = (patch: Partial<GauntletConfig['approval']>) =>
    update((c) => ({ ...c, approval: { ...c.approval, ...patch } }));

  const setKind = (kind: ApprovalPolicyKind) => {
    const patch: Partial<GauntletConfig['approval']> = { kind };
    // Seed the fields the new policy depends on, so it is immediately valid.
    if (kind === 'weighted-consensus' && Object.keys(approval.weights).length === 0) {
      patch.weights = Object.fromEntries(reviewers.map((r) => [r.id, r.authority]));
    }
    if (kind === 'sequential-signoff' && approval.signoffOrder.length === 0) {
      patch.signoffOrder = reviewers.map((r) => r.id);
    }
    if (kind === 'lead-decides' && !approval.deciderId) {
      patch.deciderId = ctx.lead?.id ?? reviewers[0]?.id;
    }
    if (kind === 'hybrid' && approval.hybridGateIds.length === 0) {
      patch.hybridGateIds = reviewers.filter((r) => r.mandatoryApproval).map((r) => r.id);
    }
    update((c) => ({ ...c, approval: { ...c.approval, ...patch } }));
  };

  return (
    <div className="stack-lg">
      <div className="approval-list" role="radiogroup" aria-label="Approval policy">
        {APPROVAL_POLICIES.map((policy) => {
          const selected = approval.kind === policy.id;
          return (
            <button
              key={policy.id}
              type="button"
              className="approval-option"
              role="radio"
              aria-checked={selected}
              onClick={() => setKind(policy.id)}
            >
              <span className="approval-option-marker" aria-hidden="true">
                {selected && <Check size={12} />}
              </span>
              <span className="approval-option-text">
                <span className="approval-option-name">{policy.label}</span>
                <span className="approval-option-blurb">{policy.blurb}</span>
                <span className="approval-option-consequence">{policy.consequence}</span>
              </span>
            </button>
          );
        })}
      </div>

      {/* Policy-specific settings */}
      {approval.kind === 'supermajority' && (
        <NumberInput
          label="Percentage that must approve"
          value={approval.supermajorityPercent}
          onChange={(v) => patchApproval({ supermajorityPercent: Math.max(50, Math.min(100, v)) })}
          min={50}
          max={100}
          step={5}
          suffix="%"
          help={`Of ${reviewers.length} reviewers, that means at least ${Math.ceil(
            (approval.supermajorityPercent / 100) * reviewers.length,
          )} must approve.`}
        />
      )}

      {approval.kind === 'weighted-consensus' && (
        <section className="wizard-section">
          <h2 className="wizard-section-title">Vote weights</h2>
          <p className="field-help">
            Give reviewers more or less say. Set weights carefully — one large weight means that
            reviewer effectively decides alone.
          </p>
          <div className="stack-sm">
            {reviewers.map((r) => (
              <div className="weight-row" key={r.id}>
                <span className="weight-name">
                  {r.name}
                  <Badge>{roleById(r.roleType).label}</Badge>
                </span>
                <input
                  type="range"
                  className="range-input"
                  min={0}
                  max={10}
                  value={approval.weights[r.id] ?? r.authority}
                  aria-label={`Vote weight for ${r.name}`}
                  onChange={(e) =>
                    patchApproval({
                      weights: { ...approval.weights, [r.id]: Number(e.target.value) },
                    })
                  }
                />
                <span className="weight-value">{approval.weights[r.id] ?? r.authority}</span>
              </div>
            ))}
          </div>
          <NumberInput
            label="Approving weight required"
            value={Math.round(approval.weightedThreshold * 100)}
            onChange={(v) => patchApproval({ weightedThreshold: Math.max(1, Math.min(100, v)) / 100 })}
            min={1}
            max={100}
            step={5}
            suffix="% of total"
          />
        </section>
      )}

      {approval.kind === 'sequential-signoff' && (
        <section className="wizard-section">
          <h2 className="wizard-section-title">Sign-off order</h2>
          <p className="field-help">
            Reviewers approve one at a time. A later reviewer never sees work that failed an earlier
            gate.
          </p>
          <ol className="signoff-list">
            {approval.signoffOrder.map((id, index) => {
              const agent = ctx.byId(id);
              if (!agent) return null;
              return (
                <li className="signoff-item" key={id}>
                  <span className="signoff-num">{index + 1}</span>
                  <span className="signoff-name">{agent.name}</span>
                  <span className="row" style={{ gap: 2 }}>
                    <button
                      type="button"
                      className="btn btn-ghost btn-sm btn-icon"
                      aria-label={`Move ${agent.name} earlier`}
                      disabled={index === 0}
                      onClick={() => {
                        const next = [...approval.signoffOrder];
                        [next[index - 1], next[index]] = [next[index], next[index - 1]];
                        patchApproval({ signoffOrder: next });
                      }}
                    >
                      ↑
                    </button>
                    <button
                      type="button"
                      className="btn btn-ghost btn-sm btn-icon"
                      aria-label={`Move ${agent.name} later`}
                      disabled={index === approval.signoffOrder.length - 1}
                      onClick={() => {
                        const next = [...approval.signoffOrder];
                        [next[index + 1], next[index]] = [next[index], next[index + 1]];
                        patchApproval({ signoffOrder: next });
                      }}
                    >
                      ↓
                    </button>
                    <button
                      type="button"
                      className="btn btn-ghost btn-sm"
                      onClick={() =>
                        patchApproval({ signoffOrder: approval.signoffOrder.filter((x) => x !== id) })
                      }
                    >
                      Remove
                    </button>
                  </span>
                </li>
              );
            })}
          </ol>
          {reviewers.filter((r) => !approval.signoffOrder.includes(r.id)).length > 0 && (
            <div className="row-wrap">
              <span className="text-sm text-tertiary">Add:</span>
              {reviewers
                .filter((r) => !approval.signoffOrder.includes(r.id))
                .map((r) => (
                  <button
                    key={r.id}
                    type="button"
                    className="chip"
                    style={{ cursor: 'pointer' }}
                    onClick={() => patchApproval({ signoffOrder: [...approval.signoffOrder, r.id] })}
                  >
                    + {r.name}
                  </button>
                ))}
            </div>
          )}
        </section>
      )}

      {approval.kind === 'lead-decides' && (
        <Select
          label="Who makes the final call?"
          value={approval.deciderId ?? ''}
          onChange={(v) => patchApproval({ deciderId: v })}
          options={config.agents
            .filter((a) => a.enabled)
            .map((a) => ({ value: a.id, label: a.name, blurb: roleById(a.roleType).label }))}
          help="This agent reads every verdict and decides. It must justify in writing any decision to finish over an open objection."
        />
      )}

      {approval.kind === 'hybrid' && (
        <section className="wizard-section">
          <h2 className="wizard-section-title">Gates that cannot be waived</h2>
          <p className="field-help">
            These reviewers must pass on objective evidence before anyone votes or decides. Their
            approval cannot be overruled.
          </p>
          <div className="stack-sm">
            {reviewers.map((r) => (
              <label key={r.id} className="checkbox-row" style={{ cursor: 'pointer' }}>
                <input
                  type="checkbox"
                  checked={approval.hybridGateIds.includes(r.id)}
                  style={{ marginTop: 3, accentColor: 'var(--accent)' }}
                  onChange={(e) =>
                    patchApproval({
                      hybridGateIds: e.target.checked
                        ? [...approval.hybridGateIds, r.id]
                        : approval.hybridGateIds.filter((x) => x !== r.id),
                    })
                  }
                />
                <span className="switch-text">
                  <span className="switch-label" style={{ fontWeight: 'var(--weight-normal)' }}>
                    {r.name}
                  </span>
                  <span className="switch-blurb">{roleById(r.roleType).label}</span>
                </span>
              </label>
            ))}
          </div>
          <Select
            label="Once the gates pass, who finishes it?"
            value={approval.hybridFinalStage}
            onChange={(v) => patchApproval({ hybridFinalStage: v as 'consensus' | 'human' | 'lead' })}
            options={[
              { value: 'lead', label: 'The lead agent decides', blurb: 'Fast, and it must justify itself' },
              { value: 'consensus', label: 'The reviewers vote', blurb: 'Shared judgement' },
              { value: 'human', label: 'You decide', blurb: 'Nothing finishes without you' },
            ]}
          />
        </section>
      )}

      {advanced && (
        <section className="wizard-section">
          <h2 className="wizard-section-title">Objection handling</h2>
          <Toggle
            label="A single reviewer can block completion"
            checked={approval.allowVeto}
            onChange={(v) => patchApproval({ allowVeto: v })}
            blurb="Prevents a real problem being outvoted. Without it, a genuine defect can be approved past."
          />
          {approval.allowVeto && (
            <NumberInput
              label="Escalate a persistent block after"
              value={approval.vetoEscalatesAfter}
              onChange={(v) => patchApproval({ vetoEscalatesAfter: Math.max(1, v) })}
              min={1}
              max={20}
              suffix="rounds"
              help="If the same reviewer blocks this many rounds running, the run escalates rather than looping forever."
            />
          )}
          <Toggle
            label="A person must give final approval"
            checked={approval.requiresHumanFinal}
            onChange={(v) => patchApproval({ requiresHumanFinal: v })}
            blurb="On top of whatever the agents decide. Add a checkpoint in step 7 so the run knows where to stop and ask."
          />
        </section>
      )}

      <Callout tone="ok" title="What the agent will be told">
        The work is complete when <strong>{completionSentence(ctx)}</strong>.
        {ctx.blockingReviewers.length === 0 && approval.kind === 'all-mandatory' && (
          <>
            {' '}
            No reviewer is currently marked as required, so nothing would actually gate completion.
            Mark at least one reviewer as required in step 4.
          </>
        )}
      </Callout>

      <Callout tone="info" title="Running out of rounds is not approval">
        {approvalById(approval.kind).label} defines success. If the loop hits its limit before that
        condition is met, the generated prompt requires an honest unresolved status — blocked,
        incomplete, or needing your decision — rather than a claim of completion.
      </Callout>
    </div>
  );
}
